[package]
name = "playground"
version = "0.1.0"
authors = ["strohs <strohs1@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.7"
futures = "0.3.1"
async-std = { version = "1.2.0", features = ["attributes"] }
surf = "1.0"
regex = "1"